audio_voices_ids = {
    "en-US": {"FEMALE": "Kendra", "MALE": "Joey"},
    "fr-FR": {"FEMALE": "Celine", "MALE": "Mathieu"},
    "es-ES": {"FEMALE": "Lucia", "MALE": "Enrique"},
    "ar-XA": {"FEMALE": "Zeina", "MALE": ""},
    "de-DE": {"FEMALE": "Marlene", "MALE": "Hans"},
    "en-GB": {"FEMALE": "Amy", "MALE": "Brian"},
    "nl-NL": {"FEMALE": "Lotte", "MALE": "Ruben"},
    "it-IT": {"FEMALE": "Carla", "MALE": "Giorgio"},
    "ja-JP": {"FEMALE": "Mizuki", "MALE": "Takumi"},
    "cmn-CN": {"FEMALE": "Zhiyu", "MALE": ""},
    "ru-RU": {"FEMALE": "Tatyana", "MALE": "Maxim"},
    "pt-BR": {"FEMALE": "Camila", "MALE": "Ricardo"},
    "da-DK": {"FEMALE": "Naja", "MALE": "Mads"},
    "ko-KR": {"FEMALE": "Seoyeon", "MALE": ""},
    "pt-PT": {"FEMALE": "Ines", "MALE": "Cristiano"},
}

tags = {
    "ADJ": "Adjactive",
    "ADP": "Adposition",
    "ADV": "Adverb",
    "AUX": "Auxiliary",
    "CCONJ": "Coordinating_Conjunction",
    "CONJ": "Coordinating_Conjunction",
    "INTJ": "Injection",
    "DET": "Determiner",
    "NOUN": "Noun",
    "NUM": "Cardinal_number",
    "PRON": "Pronoun",
    "PROPN": "Proper_noun",
    "PART": "Particle",
    "PUNCT": "Punctuation",
    "SYM": "Symbol",
    "SCONJ": "Subordinating_Conjunction",
    "VERB": "Verb",
    "O": "Other",
}
