from typing import Any, Dict, Generator, List, Literal, Optional, Union
from pydantic import BaseModel, Field, ConfigDict


class ResponseOutputContent(BaseModel):
    type: str = Field(..., description="The type of content block, e.g. 'output_text'")
    text: Optional[str] = Field(None, description="The text content")

    model_config = ConfigDict(extra="allow")


class ResponseOutputItem(BaseModel):
    """A generic output item; can be a message or other typed output."""

    type: str = Field(..., description="The type of output item")
    id: Optional[str] = Field(None, description="The ID of the output item")
    role: Optional[str] = Field(None, description="The role, if applicable")
    status: Optional[str] = Field(None, description="The status, if applicable")
    content: Optional[List[ResponseOutputContent]] = Field(
        None, description="Content blocks, if applicable"
    )

    model_config = ConfigDict(extra="allow")


class ResponsesUsage(BaseModel):
    input_tokens: Optional[int] = Field(
        None, description="Number of tokens in the input"
    )
    output_tokens: Optional[int] = Field(
        None, description="Number of tokens in the output"
    )
    total_tokens: Optional[int] = Field(
        None, description="Total number of tokens used"
    )
    input_tokens_details: Optional[Dict[str, Any]] = Field(
        None, description="Detailed breakdown of input tokens"
    )
    output_tokens_details: Optional[Dict[str, Any]] = Field(
        None, description="Detailed breakdown of output tokens"
    )

    model_config = ConfigDict(extra="allow")


class ResponsesDataClass(BaseModel):
    id: str = Field(..., description="Unique identifier for this response")
    object: Optional[str] = Field(None, description="Object type, e.g. 'response'")
    created_at: Optional[int] = Field(
        None, description="Unix timestamp for when the response was created"
    )
    status: Optional[str] = Field(
        None, description="The status of the response, e.g. 'completed'"
    )
    model: Optional[str] = Field(None, description="The model used for the response")
    output: List[ResponseOutputItem] = Field(
        default_factory=list,
        description="List of output items generated by the model",
    )
    usage: Optional[ResponsesUsage] = Field(
        None, description="Token usage statistics for the response"
    )
    # Fields echoed back from the request
    error: Optional[Dict[str, Any]] = Field(
        None, description="Error information if the response failed"
    )
    incomplete_details: Optional[Dict[str, Any]] = Field(
        None, description="Details about why the response is incomplete"
    )
    instructions: Optional[str] = Field(
        None, description="System instructions used for the response"
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None, description="Metadata attached to the response"
    )
    parallel_tool_calls: Optional[bool] = Field(
        None, description="Whether parallel tool calls were enabled"
    )
    temperature: Optional[float] = Field(None, description="Sampling temperature used")
    tool_choice: Optional[Union[str, Dict[str, Any]]] = Field(
        None, description="Tool choice configuration"
    )
    tools: Optional[List[Any]] = Field(
        None, description="Tools available to the model"
    )
    top_p: Optional[float] = Field(None, description="Nucleus sampling parameter used")
    max_output_tokens: Optional[int] = Field(
        None, description="Maximum output tokens limit"
    )
    previous_response_id: Optional[str] = Field(
        None, description="The ID of the previous response in a session"
    )
    reasoning: Optional[Dict[str, Any]] = Field(
        None, description="Reasoning configuration used"
    )
    text: Optional[Dict[str, Any]] = Field(
        None, description="Text formatting options used"
    )
    truncation: Optional[Literal["auto", "disabled"]] = Field(
        None, description="Truncation strategy used"
    )
    store: Optional[bool] = Field(
        None, description="Whether the response is stored server-side"
    )
    user: Optional[str] = Field(None, description="End-user identifier")

    model_config = ConfigDict(extra="allow")


class DeleteResponseDataClass(BaseModel):
    id: Optional[str] = Field(None, description="The ID of the deleted response")
    object: Optional[str] = Field(None, description="Object type, e.g. 'response'")
    deleted: Optional[bool] = Field(
        None, description="Whether the response was successfully deleted"
    )


class StreamResponses(BaseModel):
    stream: Generator

    model_config = ConfigDict(arbitrary_types_allowed=True)
