from typing import Any, Dict, Generator, List, Literal, Optional, Union
from pydantic import BaseModel, Field, ConfigDict


class ResponseOutputContent(BaseModel):
    type: str = Field(..., description="The type of content block, e.g. 'output_text'")
    text: Optional[str] = Field(None, description="The text content")


class ResponseOutputMessage(BaseModel):
    type: Literal["message"] = Field("message", description="The type of output item")
    id: Optional[str] = Field(None, description="The ID of the output message")
    role: Optional[str] = Field(None, description="The role of the message author")
    status: Optional[str] = Field(None, description="The status of the message")
    content: List[ResponseOutputContent] = Field(
        default_factory=list,
        description="The content blocks of the output message",
    )


class ResponseOutputItem(BaseModel):
    """A generic output item; can be a message or other typed output."""

    type: str = Field(..., description="The type of output item")
    id: Optional[str] = Field(None, description="The ID of the output item")
    role: Optional[str] = Field(None, description="The role, if applicable")
    status: Optional[str] = Field(None, description="The status, if applicable")
    content: Optional[List[ResponseOutputContent]] = Field(
        None, description="Content blocks, if applicable"
    )

    model_config = ConfigDict(extra="allow")


class ResponsesUsage(BaseModel):
    input_tokens: Optional[int] = Field(
        None, description="Number of tokens in the input"
    )
    output_tokens: Optional[int] = Field(
        None, description="Number of tokens in the output"
    )
    total_tokens: Optional[int] = Field(
        None, description="Total number of tokens used"
    )
    input_tokens_details: Optional[Dict[str, Any]] = Field(
        None, description="Detailed breakdown of input tokens"
    )
    output_tokens_details: Optional[Dict[str, Any]] = Field(
        None, description="Detailed breakdown of output tokens"
    )


class ResponsesDataClass(BaseModel):
    id: str = Field(..., description="Unique identifier for this response")
    object: str = Field(..., description="Object type, e.g. 'response'")
    created_at: Optional[int] = Field(
        None, description="Unix timestamp for when the response was created"
    )
    status: Optional[str] = Field(
        None, description="The status of the response, e.g. 'completed'"
    )
    model: Optional[str] = Field(None, description="The model used for the response")
    output: List[ResponseOutputItem] = Field(
        default_factory=list,
        description="List of output items generated by the model",
    )
    usage: Optional[ResponsesUsage] = Field(
        None, description="Token usage statistics for the response"
    )
    previous_response_id: Optional[str] = Field(
        None, description="The ID of the previous response in a session"
    )

    model_config = ConfigDict(extra="allow")


class StreamResponses(BaseModel):
    stream: Generator

    model_config = ConfigDict(arbitrary_types_allowed=True)
