tags = {
    "ADJ": "adjective",
    "ADJPOS": "possessive adjective",
    "ADJDEM": "demonstrative adjective",
    "ADJNUM": "numeral adjective",
    "ADJVPP": "adjective or verb with past participle",
    "ADJWH": "interrogative adjective",
    "ADV": "adverb",
    "ADVHW": "interrogative adverb",
    "AUX": "auxiliary",
    "CC": "co-ordinating conjunction",
    "CS": "subordinating conjunction",
    "CL": "clitic",
    "CLS": "subject clitic",
    "CLO": "object clitic",
    "CLR": "reflexive clitic",
    "DET": "determiner",
    "DETI": "indeterminate determiner",
    "DETD": "demonstrative determiner",
    "DETWH": "interrogative determiner",
    "I": "interjection",
    "NC": "common noun",
    "NPP": "proper noun",
    "P": "preposition",
    "PD": "preposition and determiner",
    "PONCT": "punctuation",
    "PRO": "pronoun",
    "PROREL": "relative pronoun",
    "PROWH": "interrogative pronoun",
    "SEMAUX": "semi-auxiliary",
    "V": "verb",
    "VIMP": "imperative verb",
    "VINF": "infinitive verb",
    "VPP": "past participle verb",
    "VPR": "present participle verb",
    "VS": "subjunctive verb",
}
