tags = {
    "C": "conjunction",
    "CC": "co-ordinating conjunction",
    "CD": "number",
    "CLO": "pronoun object",
    "CLS": "pronoun",
    "D": "determiner",
    "JJ": "adjective",
    "N": "common noun",
    "NP": "proper noun",
    "PUNCT": "punctuation",
    "P": "preposition",
    "PD": "pronom define",
    "PROREL": "pronom relative",
    "RB": "adverb",
    "RB_WH": "adverb question",
    "SYM": "symbols",
    "UH": "interjection",
    "V": "verb",
    "VINF": "infinitive verb",
    "VP": "verb participe past",
}
