audio_voice_ids = {
    "en-US": {"FEMALE": "en-US-ZiraRUS", "MALE": "en-US-BenjaminRUS"},
    "fr-FR": {"FEMALE": "fr-FR-Julie-Apollo", "MALE": "fr-FR-Paul-Apollo"},
    "es-ES": {"FEMALE": "es-ES-Laura-Apollo", "MALE": "es-ES-Pablo-Apollo"},
    "ar-XA": {"FEMALE": "ar-EG-Hoda", "MALE": "ar-SA-Naayf"},
    "de-DE": {"FEMALE": "de-DE-Hedda", "MALE": "de-DE-Stefan-Apollo"},
    "en-GB": {"FEMALE": "en-GB-Susan-Apollo", "MALE": "en-GB-George-Apollo"},
    "nl-NL": {"FEMALE": "nl-NL-HannaRUS", "MALE": ""},
    "it-IT": {"FEMALE": "it-IT-LuciaRUS", "MALE": "it-IT-Cosimo-Apollo"},
    "ja-JP": {"FEMALE": "ja-JP-Ayumi-Apollo", "MALE": "ja-JP-Ichiro-Apollo"},
    "cmn-CN": {"FEMALE": "zh-CN-HuihuiRUS", "MALE": "zh-CN-Yaoyao-Apollo"},
    "ru-RU": {"FEMALE": "ru-RU-Irina-Apollo", "MALE": "ru-RU-Pavel-Apollo"},
    "pt-BR": {"FEMALE": "pt-BR-HeloisaRUS", "MALE": "pt-BR-Daniel-Apollo"},
    "da-DK": {"FEMALE": "da-DK-HelleRUS", "MALE": ""},
    "ko-KR": {"FEMALE": "ko-KR-HeamiRUS", "MALE": ""},
    "pt-PT": {"FEMALE": "pt-PT-HeliaRUS", "MALE": ""},
}
