from .amazon import AmazonApi
from .google import GoogleApi
from .microsoft import MicrosoftApi
from .connexun import ConnexunApi
from .emvista import EmvistaApi
from .ibm import IbmApi
from .huggingface import HuggingfaceApi
from .affinda import AffindaApi
from .clarifai import ClarifaiApi
from .base64 import Base64Api
from .deepl import DeeplApi
from .lettria import LettriaApi
from .meaningcloud import MeaningcloudApi
from .mindee import MindeeApi
from .tabscanner import TabscannerApi
from .oneai import OneaiApi
from .openai import OpenaiApi
from .neuralspace import NeuralSpaceApi
from .revai import RevAIApi
from .symbl import SymblApi
from .smartclick import SmartClickApi
from .voci import VociApi
from .dataleon import DataleonApi
from .api4ai import Api4aiApi
from .sentisight import SentiSightApi
from .picpurify import PicpurifyApi
from .phedone import PhedoneApi
from .voxist import VoxistApi
from .modernmt import ModernmtApi
from .hireability import HireabilityApi
from .assembly import AssemblyApi
from .deepgram import DeepgramApi
from .cohere import CohereApi
from .skybiometry import SkybiometryApi
from .deepai import DeepAIApi
from .stabilityai import StabilityAIApi
from .veryfi import VeryfiApi
from .klippa import KlippaApi
from .rossum import RossumApi
from .lovoai import LovoaiApi
from .prowritingaid import ProWritingAidApi
from .writesonic import WritesonicApi
from .speechmatics import SpeechmaticsApi
from .tenstorrent import TenstorrentApi
from .facepp import FaceppApi
from .originalityai import OriginalityaiApi

# THIS NEEDS TO BE DONE AUTOMATICALLY
